<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('keys', function (Blueprint $table) {
            $table->id();
            $table->string('initial_key'); //generated by client software my secret $key = "my secret key";
            $table->string('activated_key'); // empty init, Generated after payment manual MDX 537aee53df5b5f4046c64a7a3f9d07f7 $encrypted_key = md5($key);
            $table->string('device_number'); // generated by client software
            $table->date('expiration_date'); // date of installation client softwre+30Day
            $table->boolean('auto_renewal'); // default true

            $table->unsignedBigInteger('order_id');
            $table->foreign('order_id')
            ->references('id')
            ->on('orders')
            ->onDelete('cascade');

            $table->unsignedBigInteger('key_statuses_id');
            $table->foreign('key_statuses_id')
            ->references('id')
            ->on('key_statuses')
            ->onDelete('cascade');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('key');
    }
};
